### ISSUE TITLE
Fill in User data to include the players birthday 

### ISSUE THREAD

**Issue by riFaulkner** [riFaulkner/sports-kernel#25]
This will allow us to show how old players are in the app

**Comment by riFaulkner** [comment]
Lets also make sure they have a correct team currently

**Comment by KBThree13** [comment]
This should be up to date. I did find a couple incorrect birthdays in a random sample, so I might need to find another source

**Comment by riFaulkner** [comment]
When we talked about this we had discussed adding to the GQL a function that will take the birthdate and transform it into an 'age' field. That way we don't have to do that math on the FE.

Can you add that functionality to the GQL query? Then we can close this out.

**Comment by riFaulkner** [comment]
Added this functionality as apart of the contract creation flow.
