### ISSUE TITLE
Team contract meta data seems to only account for 4yr contracts

### ISSUE THREAD

**Issue by KBThree13** [riFaulkner/sports-kernel#34]
I added a couple mock contracts at 2yr lengths and the meta data updated at 1/4th the total cost of the contract

**Comment by riFaulkner** [comment]
I found an out of bounds error in my logic, try checking out the data now. I think that fixing that helped update for all contracts

**Comment by KBThree13** [comment]
Checked it! Looks good! I think the numbers match Ramzi's owner summary too.
