### ISSUE TITLE
Tab views to menu button for mobile

### ISSUE THREAD

**Issue by KBThree13** [riFaulkner/sports-kernel#35]
The tabs don't render correctly in mobile, looks like they get clipped. Is it possible to move those views to the menu button for mobile only?

**Comment by riFaulkner** [comment]
Hey Kyle can you add some screenshots of what you're seeing?

**Comment by KBThree13** [comment]
![image](https://user-images.githubusercontent.com/36335011/180665838-71ef8c30-f4f2-40dc-83e3-3a4ec06fb1cc.jpeg)

It sort of clips the top menu, and then it's not super intuitive that you need to scroll to see additional options.

**Comment by riFaulkner** [comment]
#92 Addresses the issue. Let me know what you think @KBThree13
