### ISSUE TITLE
Rules View

### ISSUE THREAD

**Issue by KBThree13** [riFaulkner/sports-kernel#37]
Create a new text or markdown object with league rules, create matching view on the front end

**Comment by riFaulkner** [comment]
I know you were pretty close on this before. Do you have a PR open for it? If so you can tag this task in the PR by using #_taskNumber_

**Comment by KBThree13** [comment]
@riFaulkner I actually already merged this as part of #57. Take a look and let me know what you think and we can close this one. I think I might create a new issue wrt the rules to handle some automation of rule additions and rule change tracking.

**Comment by riFaulkner** [comment]
Right on looks good, can you close this so we can keep track of what still needs to be done.
