### ISSUE TITLE
Create Alph Google Form

### ISSUE THREAD

**Issue by riFaulkner** [riFaulkner/sports-kernel#63]
Alpha will be an important phase for us to collect data and let other users try out the app. I'd like to open up to only a few people that are willing to give feedback around the system, maybe 3 people other than you and I. Before we allow broader access I'd like to have a clear path for feedback to get to us so during the alpha we can focus on implementing the feedback instead of collecting it.

I think Eric has already created an account, he seems eager so we should include him. I think the other obvious candidate is Ramsey, since he's been managing the league. Should we send out an email asking for who else might want to join alpha? I think only a few weeks of alpha would be good enough before opening everyone up to the 'beta phase'.

@KBThree13 we should talk more about what each of these phases really means at a high level in our next meet.

**Comment by KBThree13** [comment]
@riFaulkner I think we start with Conner (he's actually in Software Consulting), Eric, Jeff, and Ramzi. The latter three have been commissioners on other leagues so they'll have some good perspective and I think they'll be more than willing to provide feedback.

**Comment by riFaulkner** [comment]
Sounds good, I've updated the timelines for Alpha and beta releases. We should work to clearly define these milestones when we meet next. My initial thought is that we should have a month for Alpha and then beta would have a little over a month. With the target of launching beta to everyone when the NFL preseason starts Aug 4.

**Comment by riFaulkner** [comment]
Link to this form from email for alpha. Also have a link on the site

**Comment by riFaulkner** [comment]
@KBThree13 the google form you made looks great! Can you link it here and close this out?

**Comment by KBThree13** [comment]
[Google Form Link](https://docs.google.com/forms/d/e/1FAIpQLSe-RZC4weh9AtTJBpOY_NP7d_8h6TPV-BxwVa-UEWRNSMmB0Q/viewform?usp=sf_link)
