### ISSUE TITLE
Implement Player scoring

### ISSUE THREAD

**Issue by riFaulkner** [riFaulkner/sports-kernel#65]
Prior to the season it would be great to have a scoring engine in place. This may be something we need to develop during the season, though...

**Comment by KBThree13** [comment]
Sounds like a good plan - much like the player team information source, we'll need to determine:
- What is our source for this information?
- How do we want to pull from this source? Separate function or job? 
- What's our target data latency and data freshness for beta and ongoing?

**Comment by riFaulkner** [comment]
Absolutely, I image this will likely be part of, or similar to the data pipeline for the player data. I'd like to store the players stats rather than storing specific scoring here. That way if scoring changes in the future we can give accurate data around what a player's stats would have been.
