### ISSUE TITLE
Generate a code for new users to join team

### ISSUE THREAD

**Issue by riFaulkner** [riFaulkner/sports-kernel#81]
New user onboard flow pt. 1

Add a league management tool called `Generate Team Access Codes` this should live in the league management tab.

add a drop down for the user to select the team, this was done in the first step of the create contract flow so that should be a good spot to look for the GQL to use.
And the role. We'll do roles of `League Manager` `Team Owner`

On submit of these items; leagueId, teamId and role we'll need to do the logic to to BE.

1. Make sure there is a directive on the GQL mutation so only a League Manager can make this call.
2. Generate a code, we'll use B64 encoding for this. My suggestion would be to make it something like this b64Encode(`leagueId,teamId,role,randomstring`)
3. After the code is generated add it to the team object under a new field called `activationCodes` 
4. Return the activation code

**Comment by riFaulkner** [comment]
@KBThree13 i added some details here for generating the code to be used in the new use onboarding flow. Let me know if I can clarify anything further.

**Comment by KBThree13** [comment]
@riFaulkner I'm guessing that 'On Submit' I'll need some sort of custom GQL Query on the BE that will go through the workflow you describe correct?

**Comment by KBThree13** [comment]
@riFaulkner makes sense, so then additional steps beyond this would be:

5. Make 'Join League' FE components (simple form entry)
6. Make GQL mutation for associating the user to a team with the code, once activated
7. Update team 'OwnerID' with the user that activated the code

Anything else here? I imagine we'll then need to automatically be able to then update the 'My Team' page based on that activation?
