### ISSUE TITLE
Rerun Player data import script

### ISSUE THREAD

**Issue by riFaulkner** [riFaulkner/sports-kernel#84]
Rerun the player data import script updating the format from camelCase to PascelCase this is how our GQL backend is saving the data so it will help with adding consistency.

**Comment by riFaulkner** [comment]
Side note for this, I know of a player that did change their name this last off season. Since we're using player names to seed the ID we should update his name in the spread sheet before running this query so it will be seeded correctly in our DB. Donte Harris (NO) is now Donte Harty.

There may be others but I know of at least this one case.

**Comment by KBThree13** [comment]
Donezo!
